"""
Verbatim DFM/JFA fixtures lifted from the minimal sample
(Form_Template_-_Form.jfa). These are the byte-precise templates that
Profile is known to accept; we splice them into generated forms unchanged.
"""
from __future__ import annotations
import base64

# OBSV 100503 — verbatim NZDF context row from the minimal sample.
# 44 fields, [3]='4474196' (own id), [5]='52' (semantics unknown), [9]='NM=NZDF'.
# This row is treated as a "tenancy marker" — Profile re-resolves on import.
NZDF_CONTEXT_ROW = 'OBSV\t2\t100503\t4474196\t\t52\t\t\t\tNM=NZDF\t\t2147483647\t0\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'
NZDF_CONTEXT_ROW_ID = '4474196'
NZDF_CONTEXT_ROW_NM = 'NZDF'

# DFM Macros.Strings block — 16 standard macro entries with default code
# templates, lifted verbatim from the minimal sample.
_MACROS_B64 = (
    "TWFjcm9zLlN0cmluZ3MgPSAoDQogICAgDQogICAgICAnRm9ybVByZWxvYWRNYWNybz0nIzM5JyBV"
    "c2UgdGhlIGZvbGxvd2luZyBzdGF0ZW1lbnQgdG8gaGlkZSB0aGlzIGZvcm0nICsNCiAgICAgICcg"
    "JyMxMyMxMCMzOScgYmVjYXVzZSBvZiBjb25kaXRpb25zIGV2YWx1YXRlZCBiZWZvcmUgOicjMTMj"
    "MTAjMzknICAgIFByb2ZpbGUuVmFyaScgKw0KICAgICAgJ2FibGUoIkNhbkxvYWRGb3JtIikuVmFs"
    "dWUgPSBGYWxzZScjMTMjMTAjMzkjMTMjMTAjMzknIElmIHlvdSBuZWVkIGNvZGUgdG8gZmlsbCcg"
    "Kw0KICAgICAgJyBjb250cm9scyBvZiBhIG5ldyBmb3JtIHdpdGggcHJldmlvdXNseSBlbnRlcmVk"
    "IGRhdGEsJyMxMyMxMCMzOScgcmlnaHQgYycgKw0KICAgICAgJ2xpY2sgb24geW91ciBmb3JtIGFu"
    "ZCBzZWxlY3QgIk1hY3JvIHRvIGZpbGwgaW4gcHJldmlvdXMgZGF0YSIuJyMxMyMxMA0KICAgIA0K"
    "ICAgICAgJ0Zvcm1CZWZvcmVQcmludE1hY3JvPScjMzknIEluIEJlZm9yZVByaW50IG1hY3JvIHlv"
    "dSBjYW4gaGlkZSBzb21lIGNvJyArDQogICAgICAnbnRyb2xzLCBlLmcuOiAnIzEzIzEwIzM5JyBG"
    "b3JtLkNvbnRyb2xzXygiRWRpdDEiKS5WaXNpYmxlXyA9IEZhbHNlJyMxMyMxMA0KICAgIA0KICAg"
    "ICAgJ0Zvcm1BY3Rpb25MaW5rRGVzY01hY3JvPScjMzknIFVzZSB0aGUgZm9sbG93aW5nIHN0YXRl"
    "bWVudCB0byBjcmVhdGUgJyArDQogICAgICAjMTMjMTAjMzknIGEgbmV3IENvbnRhY3QgQWN0aW9u"
    "IExpbmsgZGVzY3JpcHRpb24gZm9yIHRoaXMgZm9ybSwgZS5nLjonIzEzIzEwICsNCiAgICAgICMz"
    "OScgICAgUHJvZmlsZS5WYXJpYWJsZSgiQWN0aW9uTGlua0Rlc2MiKS5WYWx1ZSA9ICIuLi4iJyMx"
    "MyMxMA0KICAgIA0KICAgICAgJ0Zvcm1UZXh0Rm9yQ29udGFjdE1hY3JvPScjMzknIFVzZSB0aGUg"
    "Zm9sbG93aW5nIHN0YXRlbWVudCBmb3IgY3JlYXRpJyArDQogICAgICAnbmcgJyMxMyMxMCMzOScg"
    "YSBuZXcgQ29udGFjdCBUZXh0IFN0cmluZyB0byBpbnNlcnQgaXQgaW4gdGhlIGN1cnJlbnQgQ29u"
    "JyArDQogICAgICAndGFjdCBhbm5vdGF0aW9uIFJURiwgZS5nLjonIzEzIzEwIzM5JyAgICBQcm9m"
    "aWxlLlZhcmlhYmxlKCJUZXh0Rm9yQ29udGFjJyArDQogICAgICAndCIpLlZhbHVlID0gIi4uLiIn"
    "IzEzIzEwDQogICAgDQogICAgICAnRm9ybUNsb3NlUXVlcnlNYWNybz0nIzM5JyBVc2UgdGhlIGZv"
    "bGxvd2luZyBzdGF0ZW1lbnQgdG8gZm9ybSBjbG9zZSAnICsNCiAgICAgICdzdXBwcmVzc2luZywg"
    "ZS5nLjonIzEzIzEwIzM5JyAgICBQcm9maWxlLlZhcmlhYmxlKCJDYW5DbG9zZSIpLlZhbHVlID0g"
    "RmEnICsNCiAgICAgICdsc2UnIzEzIzEwDQogICAgDQogICAgICAnRm9ybUVtYmVkT2JzZXJ2YXRp"
    "b25zTWFjcm89JyMzOScgVXNlIHRoZSBmb2xsb3dpbmcgc3RhdGVtZW50IHRvIGZvcm0nICsNCiAg"
    "ICAgICcgZW1iZWRkaW5nIE9ic2VydmF0aW9ucyBpbiB0aGUgY3VycmVudCBDb250YWN0LCBlLmcu"
    "OicjMTMjMTAjMzknICAgIFByb2YnICsNCiAgICAgICdpbGUuVmFyaWFibGUoIkVtYmVkT2JzZXJ2"
    "YXRpb25zIikuVmFsdWUgPSAiQmxvb2QgUHJlc3N1cmUgMTIwLzYwJyArDQogICAgICAnOyBXZWln"
    "aHQgNzU7IEhlaWdodCAxODA7IEJQIDE0MC83MCInIzEzIzEwDQogICAgDQogICAgICAnRm9ybVBy"
    "aW50TWFjcm89JyMzOScgVXNlIHRoZSBmb2xsb3dpbmcgc3RhdGVtZW50IGlmIHRoZSBmb3JtIGNh"
    "bm5vdCAnICsNCiAgICAgICdiZSBwcmludGVkLCBlLmcuOicjMTMjMTAjMzknICAgIE1zZ2JveCAi"
    "VGhpcyBmb3JtIGNhbm5vdCBiZSBwcmludGVkIiwgdmInICsNCiAgICAgICdTeXN0ZW1Nb2RhbCwg"
    "IlByb2ZpbGUiJyMxMyMxMCMzOScgVGhlIG5leHQgdmFyaWFibGUgaXMgZGVmaW5lZCB0byBzYXkg"
    "dG8nICsNCiAgICAgICcgUHJvZmlsZSB0aGF0IGEgZm9ybSB3YXMgbm90IHByaW50ZWQnIzEzIzEw"
    "IzM5JyAgICBQcm9maWxlLlZhcmlhYmxlKCJXYXMnICsNCiAgICAgICdQcmludCIpLlZhbHVlID0g"
    "RmFsc2UnDQogICAgDQogICAgICAnRm9ybVZhbGlkYXRlU2F2ZT0nIzM5JyBVc2UgdGhlIGZvbGxv"
    "d2luZyBzdGF0ZW1lbnQgdG8gZm9ybSBzYXZlIGNhbmMnICsNCiAgICAgICdlbGxpbmcsIGUuZy46"
    "JyMxMyMxMCMzOScgICAgUHJvZmlsZS5WYXJpYWJsZSgiQ2FuU2F2ZSIpLlZhbHVlID0gRmFsc2Un"
    "IzEzIzEwIzM5ICsNCiAgICAgICcgTmV4dCB2YXJpYWJsZSBpcyBkZWZpbmVkIHRvIHNob3cgc3Rh"
    "bmRhcmQgbWVzc2FnZScjMTMjMTAjMzknIHdoZW4gdmFsaWQnICsNCiAgICAgICdhdGlvbiBvZiBz"
    "YXZlIGlzIG5vdCBzdWNjZXNzZnVsOicjMTMjMTAjMzknICAgIFByb2ZpbGUuVmFyaWFibGUoIlNo"
    "b3dNZXMnICsNCiAgICAgICdzYWdlIikuVmFsdWUgPSBUcnVlJyMxMyMxMCMzOScgdG8gc2hvdyBF"
    "cnJvck1lc3NhZ2UgeW91IGNhbiB1c2UgdGhlIG5leHQnICsNCiAgICAgICcgdmFyaWFibGVzOicj"
    "MzknICAgIFByb2ZpbGUuVmFyaWFibGUoIkNvbnRyb2xOYW1lIikuVmFsdWUgPSAiRWRpdDEiJyMx"
    "MyArDQogICAgICAjMTAjMzknICAgIFByb2ZpbGUuVmFyaWFibGUoIkVycm9yTWVzc2FnZSIpLlZh"
    "bHVlID0gIllvdSBzaG91bGQgZW50ZXInICsNCiAgICAgICcgdmFsdWUgaW50byBlZGl0IicjMTMj"
    "MTANCiAgICANCiAgICAgICdGb3JtUmVwcmVzZW50YXRpb25SdGY9JyMzOScgSW4gT25NUmVwcmVz"
    "ZW50YXRpb25SdGYgbWFjcm8geW91IGNhbiByZScgKw0KICAgICAgJ3R1cm4gUmVwcmVzZW50YXRp"
    "b24gUlRGOicjMTMjMTAjMzknICAgIFByb2ZpbGUuVmFyaWFibGUoIlJlcHJlc2VudGF0aW9uUicg"
    "Kw0KICAgICAgJ3RmIikuVmFsdWUgPSAiU29tZSBSVEYiJyMxMyMxMA0KICAgIA0KICAgICAgJ0Zv"
    "cm1RdWVyeVByaW50TWFjcm89JyMzOScgVXNlIHRoZSBmb2xsb3dpbmcgc3RhdGVtZW50IHRvIGZv"
    "cm0gcHJpbnQgJyArDQogICAgICAnY2FuY2VsbGluZywgZS5nLjonIzEzIzEwIzM5JyAgICBQcm9m"
    "aWxlLlZhcmlhYmxlKCJDYW5QcmludCIpLlZhbHVlID0gRmFsJyArDQogICAgICAnc2UnIzEzIzEw"
    "IzM5JyBOZXh0IHZhcmlhYmxlIGlzIGRlZmluZWQgdG8gc2hvdyBzdGFuZGFyZCBtZXNzYWdlJyMx"
    "MyMxMCMzOScgdG8gc2gnICsNCiAgICAgICdvdyBFcnJvck1lc3NhZ2UgeW91IGNhbiB1c2UgdGhl"
    "IG5leHQgdmFyaWFibGVzOicjMzknICAgIFByb2ZpbGUuVmFyaScgKw0KICAgICAgJ2FibGUoIkNv"
    "bnRyb2xOYW1lIikuVmFsdWUgPSAiRWRpdDEiJyMxMyMxMCMzOScgICAgUHJvZmlsZS5WYXJpYWJs"
    "ZSgiRXJybycgKw0KICAgICAgJ3JNZXNzYWdlIikuVmFsdWUgPSAiWW91IHNob3VsZCBlbnRlciB2"
    "YWx1ZSBpbnRvIGVkaXQiJyMxMyMxMA0KICAgIA0KICAgICAgJ0Zvcm1HZW5lcmF0ZVByZXZpZXdE"
    "ZXNjcmlwdGlvbj0nIzM5JyBVc2UgdGhlIGZvbGxvd2luZyBzdGF0ZW1lbnQgdG8gJyArDQogICAg"
    "ICAnZ2VuZXJhdGUgcHJldmlldywgZS5nLjonIzEzIzEwIzM5JyAgICBpZiBQcm9maWxlLlZhcmlh"
    "YmxlKCJGdWxsUGF0aFByZXZpJyArDQogICAgICAnZXciKS5WYWx1ZSA9ICJIaXN0b3J5XERpYWJl"
    "dGVzIFR5cGUiIHRoZW4nIzEzIzEwIzM5JyBOZXh0IHZhcmlhYmxlIGlzIGRlJyArDQogICAgICAn"
    "ZmluZWQgdG8gbWFrZSBkZXNjcmlwdGlvbiBpbiBwcmV2aWV3JyMxMyMxMCMzOScgICAgUHJvZmls"
    "ZS5WYXJpYWJsZSgiRGVzJyArDQogICAgICAnY3JpcHRpb25QcmV2aWV3IikuVmFsdWUgPSAiT3Vy"
    "IGRlc2NyaXB0aW9uIicjMTMjMTAjMzknIEFuZCBuZXh0IHZhcmlhYmxlJyArDQogICAgICAnIGlz"
    "IGRlZmluZWQgdG8gaGlkZSB0aGlzIGRlc2NyaXB0aW9uIGluIHByZXZpZXcnIzEzIzEwIzM5JyAg"
    "ICBQcm9maWxlLlZhJyArDQogICAgICAncmlhYmxlKCJUZXh0SGlkZSIpLlZhbHVlID0gVHJ1ZScj"
    "MTMjMTANCiAgICANCiAgICAgICdGb3JtR2VuZXJhdGVQcmV2aWV3VmFsdWU9JyMzOScgVXNlIHRo"
    "ZSBmb2xsb3dpbmcgc3RhdGVtZW50IHRvIGdlbmVyYScgKw0KICAgICAgJ3RlIHByZXZpZXcsIGUu"
    "Zy46JyMxMyMxMCMzOScgICAgaWYgUHJvZmlsZS5WYXJpYWJsZSgiRnVsbFBhdGhQcmV2aWV3Iiku"
    "VicgKw0KICAgICAgJ2FsdWUgPSAiSGlzdG9yeVxEaWFiZXRlcyBUeXBlIiB0aGVuJyMxMyMxMCMz"
    "OScgTmV4dCB2YXJpYWJsZSBpcyBkZWZpbmVkICcgKw0KICAgICAgJ3RvIG1ha2UgdmFsdWUgaW4g"
    "cHJldmlldycjMTMjMTAjMzknICAgIFByb2ZpbGUuVmFyaWFibGUoIlZhbHVlUHJldmlldyIpLicg"
    "Kw0KICAgICAgJ1ZhbHVlID0gQ29udHJvbHNfKCJFZGl0MSIpLlRleHQnIzEzIzEwDQogICAgDQog"
    "ICAgICAnRm9ybUFjY2Vzc2lvbkdldEZvcm1EYXRhPScjMzknIFVzZSB0aGUgZm9sbG93aW5nIHN0"
    "YXRlbWVudCB0byBzcGVjaWYnICsNCiAgICAgICd5IGNvbnRyb2wnIzM5J3MgcHJvcGVydHk6ICcj"
    "MTMjMTAjMzknICAgUHJvZmlsZS5WYXJpYWJsZSgiQ29udHJvbHMiKS5WYWx1ZS5JJyArDQogICAg"
    "ICAndGVtQnlOYW1lKCJlZHRBbHRDb250YWN0TmFtZSIpLlByb3BlcnRpZXMuRmluZFByb3BlcnR5"
    "KCJUZXh0IikuVicgKw0KICAgICAgJ2FsdWUnIzEzIzEwIzM5JyBNYWluVmFsdWUgYXR0cmlidXRl"
    "IGNhbiBiZSB1c2VkIGFzIGEgc2hvcnRjdXQgdG8gcHJvcGVydCcgKw0KICAgICAgJ3kgdGhhdCBy"
    "ZXByZXNlbnRzICJ2YWx1ZSInIzEzIzEwIzM5JyAoVGV4dCBmb3IgRWRpdCBvciBDb21ibywgQ2hl"
    "Y2tlZCBmbycgKw0KICAgICAgJ3IgQ2hlY2tCb3gsIENhcHRpb24gZm9yIExhYmVsIGV0Yy4nIzEz"
    "IzEwIzM5JyAgIFByb2ZpbGUuVmFyaWFibGUoIkNvbnRybycgKw0KICAgICAgJ2xzIikuVmFsdWUu"
    "SXRlbUJ5TmFtZSgiZWR0QWx0Q29udGFjdE5hbWUiKS5NYWluVmFsdWUgPSAiU2FtcGxlVmEnICsN"
    "CiAgICAgICdsdWUiJyMxMyMxMA0KICAgIA0KICAgICAgJ0Zvcm1BY2Nlc3Npb25WYWxpZGF0ZT0n"
    "IzM5JyBVc2UgdGhlIGZvbGxvd2luZyBzdGF0ZW1lbnQgdG8gc3BlY2lmeSBjJyArDQogICAgICAn"
    "b250cm9sJyMzOSdzIHByb3BlcnR5OiAnIzEzIzEwIzM5JyAgIFByb2ZpbGUuVmFyaWFibGUoIkNv"
    "bnRyb2xzIikuVmFsdWUuSXRlbScgKw0KICAgICAgJ0J5TmFtZSgiZWR0QWx0Q29udGFjdE5hbWUi"
    "KS5Qcm9wZXJ0aWVzLkZpbmRQcm9wZXJ0eSgiVGV4dCIpLlZhbHUnICsNCiAgICAgICdlJyMxMyMx"
    "MCMzOScgTWFpblZhbHVlIGF0dHJpYnV0ZSBjYW4gYmUgdXNlZCBhcyBhIHNob3J0Y3V0IHRvIHBy"
    "b3BlcnR5IHQnICsNCiAgICAgICdoYXQgcmVwcmVzZW50cyAidmFsdWUiJyMxMyMxMCMzOScgKFRl"
    "eHQgZm9yIEVkaXQgb3IgQ29tYm8sIENoZWNrZWQgZm9yIEMnICsNCiAgICAgICdoZWNrQm94LCBD"
    "YXB0aW9uIGZvciBMYWJlbCBldGMuJyMxMyMxMCMzOScgICBQcm9maWxlLlZhcmlhYmxlKCJDb250"
    "cm9scyInICsNCiAgICAgICcpLlZhbHVlLkl0ZW1CeU5hbWUoImVkdEFsdENvbnRhY3ROYW1lIiku"
    "TWFpblZhbHVlID0gIlNhbXBsZVZhbHVlJyArDQogICAgICAnIicjMTMjMTAjMzknIEVycm9yIGF0"
    "dHJpYnV0ZSBjYW4gYmUgdXNlZCB0byBzdG9yZSBtZXNzYWdlIGFib3V0IGZhaWxlZCB2JyArDQog"
    "ICAgICAnYWxpZGF0aW9uOicjMTMjMTAjMzknICAgUHJvZmlsZS5WYXJpYWJsZSgiQ29udHJvbHMi"
    "KS5WYWx1ZS5JdGVtQnlOYW1lKCJlJyArDQogICAgICAnZHRBbHRDb250YWN0TmFtZSIpLkVycm9y"
    "ID0gIkFsdCBDb250YWN0IE5hbWUgY2Fubm90IGJlIGVtcHR5IicjMTMjMTANCiAgICANCiAgICAg"
    "ICdGb3JtQWNjZXNzaW9uQ2hhbmdlVmFsaWRhdGU9JyMzOScgVXNlIHRoZSBmb2xsb3dpbmcgc3Rh"
    "dGVtZW50IHRvIHNwZScgKw0KICAgICAgJ2NpZnkgY29udHJvbCcjMzkncyBwcm9wZXJ0eTogJyMx"
    "MyMxMCMzOScgICBQcm9maWxlLlZhcmlhYmxlKCJDb250cm9scyIpLlZhbHUnICsNCiAgICAgICdl"
    "Lkl0ZW1CeU5hbWUoImVkdEFsdENvbnRhY3ROYW1lIikuUHJvcGVydGllcy5GaW5kUHJvcGVydHko"
    "IlRleHQiJyArDQogICAgICAnKS5WYWx1ZScjMTMjMTAjMzknIE1haW5WYWx1ZSBhdHRyaWJ1dGUg"
    "Y2FuIGJlIHVzZWQgYXMgYSBzaG9ydGN1dCB0byBwcm9wJyArDQogICAgICAnZXJ0eSB0aGF0IHJl"
    "cHJlc2VudHMgInZhbHVlIicjMTMjMTAjMzknIChUZXh0IGZvciBFZGl0IG9yIENvbWJvLCBDaGVj"
    "a2VkJyArDQogICAgICAnIGZvciBDaGVja0JveCwgQ2FwdGlvbiBmb3IgTGFiZWwgZXRjLicjMTMj"
    "MTAjMzknICAgUHJvZmlsZS5WYXJpYWJsZSgiQ29uJyArDQogICAgICAndHJvbHMiKS5WYWx1ZS5J"
    "dGVtQnlOYW1lKCJlZHRBbHRDb250YWN0TmFtZSIpLk1haW5WYWx1ZSA9ICJTYW1wbCcgKw0KICAg"
    "ICAgJ2VWYWx1ZSInIzEzIzEwIzM5JyBFcnJvciBhdHRyaWJ1dGUgY2FuIGJlIHVzZWQgdG8gc3Rv"
    "cmUgbWVzc2FnZSBhYm91dCBmYScgKw0KICAgICAgJ2lsZWQgdmFsaWRhdGlvbjonIzEzIzEwIzM5"
    "JyAgIFByb2ZpbGUuVmFyaWFibGUoIkNvbnRyb2xzIikuVmFsdWUuSXRlbUJ5TicgKw0KICAgICAg"
    "J2FtZSgiZWR0QWx0Q29udGFjdE5hbWUiKS5FcnJvciA9ICJBbHQgQ29udGFjdCBOYW1lIGNhbm5v"
    "dCBiZSBlbXAnICsNCiAgICAgICd0eSInIzEzIzEwDQogICAgDQogICAgICAnRm9ybUFjY2Vzc2lv"
    "bkFmdGVyU2F2ZT0nIzM5JyBVc2UgdGhlIGZvbGxvd2luZyBzdGF0ZW1lbnQgdG8gc3BlY2lmeSAn"
    "ICsNCiAgICAgICdjb250cm9sJyMzOSdzIHByb3BlcnR5OiAnIzEzIzEwIzM5JyAgIFByb2ZpbGUu"
    "VmFyaWFibGUoIkNvbnRyb2xzIikuVmFsdWUuSXRlJyArDQogICAgICAnbUJ5TmFtZSgiZWR0QWx0"
    "Q29udGFjdE5hbWUiKS5Qcm9wZXJ0aWVzLkZpbmRQcm9wZXJ0eSgiVGV4dCIpLlZhbCcgKw0KICAg"
    "ICAgJ3VlJyMxMyMxMCMzOScgTWFpblZhbHVlIGF0dHJpYnV0ZSBjYW4gYmUgdXNlZCBhcyBhIHNo"
    "b3J0Y3V0IHRvIHByb3BlcnR5ICcgKw0KICAgICAgJ3RoYXQgcmVwcmVzZW50cyAidmFsdWUiJyMx"
    "MyMxMCMzOScgKFRleHQgZm9yIEVkaXQgb3IgQ29tYm8sIENoZWNrZWQgZm9yICcgKw0KICAgICAg"
    "J0NoZWNrQm94LCBDYXB0aW9uIGZvciBMYWJlbCBldGMuJyMxMyMxMCMzOScgICBQcm9maWxlLlZh"
    "cmlhYmxlKCJDb250cm9scycgKw0KICAgICAgJyIpLlZhbHVlLkl0ZW1CeU5hbWUoImVkdEFsdENv"
    "bnRhY3ROYW1lIikuTWFpblZhbHVlID0gIlNhbXBsZVZhbHUnICsNCiAgICAgICdlIicjMTMjMTAp"
)

MACROS_BLOCK = base64.b64decode(_MACROS_B64).decode('utf-8')


# DFM root form property block — everything before "Macros.Strings = (".
# {caption}, {client_w}, {client_h} are substituted at format time.
ROOT_FORM_PROPS = (
    "object IVisualForm: TIVisualForm\r\n"
    "  Left = 0\r\n"
    "  Top = 0\r\n"
    "  Caption = '{caption}'\r\n"
    "  ClientHeight = {client_h}\r\n"
    "  ClientWidth = {client_w}\r\n"
    "  Color = clBtnFace\r\n"
    "  KeyPreview = True\r\n"
    "  OldCreateOrder = False\r\n"
    "  PopupMenu = RunTimePopupMenu\r\n"
    "  NeedToSave = True\r\n"
    "  RepresentationMethod = rmStructuredText\r\n"
    "  PrintMethod = pmDefault\r\n"
    "  PaperName = 'Undefined'\r\n"
    "  PaperID = 0\r\n"
    "  PaperWidth = 0\r\n"
    "  PaperHeight = 0\r\n"
    "  PrintPaperSize = 'Default'\r\n"
    "  PrintPaperID = 0\r\n"
    "  "
)


# After macros: PixelsPerInch, TextHeight, then NoteBook + TPage + Page_1 panel.
# {nb_w}, {nb_h} substituted at format time — the scrollable canvas size.
NOTEBOOK_PRELUDE = (
    "\r\n"
    "  PixelsPerInch = 96\r\n"
    "  TextHeight = 13\r\n"
    "  object aNoteBook: TICDONoteBook\r\n"
    "    Left = 0\r\n"
    "    Top = 0\r\n"
    "    Width = {nb_w}\r\n"
    "    Height = {nb_h}\r\n"
    "    Color = clGray\r\n"
    "    ParentColor = False\r\n"
    "    TabOrder = 0\r\n"
    "    OnPageChanged = aNoteBookPageChanged\r\n"
    "    object TPage\r\n"
    "      Left = 0\r\n"
    "      Top = 0\r\n"
    "      Caption = 'Page_1'\r\n"
    "      object Page_1: TICDOPanel\r\n"
    "        Name = 'Page_1'\r\n"
    "        Left = 0\r\n"
    "        Top = 0\r\n"
    "        Width = {nb_w}\r\n"
    "        Height = {nb_h}\r\n"
    "        Align = alClient\r\n"
    "        BevelOuter = bvNone\r\n"
    "        Color = clWhite\r\n"
    "        TabOrder = 0\r\n"
)


# Closing "end" sequence for Page_1 / TPage / NoteBook / IVisualForm.
DFM_CLOSING = (
    "      end\r\n"
    "    end\r\n"
    "  end\r\n"
    "end\r\n"
)
